trigger:
  - main

pool:
  name: Default
  demands: 
  - agent.name -equals Agent 

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add commands here
    echo to build and test
    echo your project.
  displayName: 'Run a multi-line script'
